# List of world names where this plugin should be active.
# An empty list [] means the plugin is disabled everywhere.
# Example:
# enabled-worlds:
#   - "world"
#   - "world_nether"
#   - "world_the_end"
enabled-worlds:
  - "world"

integrations:
  huskhomes: false

llm:
  apiKey: ""
  baseUrl: "http://172.20.2.104:8000"
  modelName: "qwen3-coder"