main: com.ionsignal.minecraft.ionnerrus.IonNerrus
name: IonNerrus
version: 0.0.9-alpha.1
api-version: "1.21.8"
author: Ion Signal
description: An LLM powered NPC decision engine
depend: []
softdepend: [FancyHolograms, Terra]
commands:
  nerrus:
    description: Manages Nerrus agents and their tasks.
    usage: "/<command> <spawn|remove|stop|getblock|follow|give|ask|do|list> ..."
    aliases: [ionnerrus]
    permission: ionnerrus.admin
permissions:
  ionnerrus.admin:
    description: Allows usage of all IonNerrus commands.
    default: op
