name: IonCore
version: '${version}'
api-version: '${api}'
main: com.ionsignal.minecraft.ioncore.IonCore
loader: com.ionsignal.minecraft.ioncore.IonCoreLoader
bootstrapper: com.ionsignal.minecraft.ioncore.IonCoreBootstrap
author: IonSignal
description: 'Core framework for Ion Signal plugins'
website: https://github.com/ionsignal/ioncore
permissions:
  ioncore.admin:
    description: Allows usage of all IonCore commands.
    default: op
