main: com.ionsignal.minecraft.ioncore.IonCore
name: IonCore
version: "${version}"
api-version: "1.21"
description: "Core framework for Ion Signal plugins"
author: Oliver Dyla
website: https://github.com/ionsignal/ioncore
