main: com.ionsignal.minecraft.ionnerrus.IonNerrus
name: IonNerrus
version: "${version}"
api-version: "${api}"
author: Ion Signal
description: "${description}"
depend: [IonCore]
softdepend: [FancyHolograms, Terra]
commands:
  nerrus:
    description: Manages Nerrus agents and their tasks.
    usage: "/<command> <spawn|remove|stop|getblock|follow|give|ask|do|list> ..."
    aliases: [ionnerrus]
    permission: ionnerrus.admin
permissions:
  ionnerrus.admin:
    description: Allows usage of all IonNerrus commands.
    default: op
